common:
  dev: true
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUruULBEuddultickzyGCawEOZrRDDXUU2sR2fDwunz+zdN7dp1ahc8N1bbr5fki3z5RJDpAHezmRZYAKxrBUg+yk379a3QZRFB888crAJD7QVMozyln6GTPijWTgOdzgswxK3wmfAyZso4K2zzqR84xLzr07RWcld4FSpF9Ij2QIDAQAB
spring:
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 50
  #数据源
  datasource:
    name: shop
    url: jdbc:mysql://120.77.173.16:3306/my_shop?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    maxActive: 50
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: select 'x'
redisson:
  ip: 127.0.0.1
  port: 6379
  mode: single
logging:
  level:
    com.rain.platform: INFO
